---
title: "Explainable AI"
author: "LK"
date: "2022-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load the libraries

library(tidyverse)  # Core
library(janitor)    # Clean names
library(tidymodels) # Modeling
library(DALEX)      # Explainer
library(modelDown)  # Explainable AI Report

```

```{r}
#Load data

customer_churn_tbl <- read_csv("https://raw.githubusercontent.com/business-science/free_r_tips/master/051_survival_plots/data/customer_churn.csv") %>%
    clean_names() %>%
    mutate_if(is.character, as_factor)

customer_churn_tbl
```

```{r}
##Create model recipe

recipe_spec <- recipe(churn ~ ., data = customer_churn_tbl) %>%
    step_rm(customer_id) %>%
    step_dummy(all_nominal_predictors(), one_hot = TRUE)

recipe_spec %>% prep() %>% bake(customer_churn_tbl)
```
```{r}
#Random forest 

model_spec <- rand_forest(
        mode = "classification",
        mtry = 4
    ) %>%
    set_engine(engine = "randomForest")
```

```{r}
#Putting everything into a tidyworkflow

wflw_fit_rf <- workflow() %>%
    add_recipe(recipe_spec) %>%
    add_model(model_spec) %>%
    fit(customer_churn_tbl)

wflw_fit_rf %>% predict(customer_churn_tbl, type= "prob")




```

```{r}
#Custom predict function

pred_func <- function(model, newdata) {
    predict(model, newdata, type = "prob") %>% pull(2)
}

pred_func(wflw_fit_rf, head(customer_churn_tbl))

```

```{r}
#DALEX Explainer

explain_rf <- explain(
    model            = wflw_fit_rf,
    data             = customer_churn_tbl %>%
        select(-churn),
    y                = as.numeric(customer_churn_tbl$churn),
    predict_function = pred_func,
    label            = "Random Forest"
)


```


```{r}
#Output

library(modelDown)
library(archivist)

modelDown::modelDown(
    explain_rf,
    modulesb= c("auditor","drifter","model_performance","variable_importance", "variable_response"),
    output_folder = tempdir(), 
    repository_name = "app", 
    remote_repository_path = "C:/Users/karanil/Documents/gitrepo/Explainable AI",
    device = "png",
    should_open_website = interactive())

```


















